INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [11/Feb/2021 19:09:37] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Feb/2021 19:09:37] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR:__main__:Exception on /uploader [POST]
Traceback (most recent call last):
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<ipython-input-5-64287bea518b>", line 49, in upload
    return process(f.filename)
  File "<ipython-input-5-64287bea518b>", line 54, in process
    listFinal = gd.startFetchingDetails(filename)
NameError: name 'gd' is not defined
INFO:werkzeug:127.0.0.1 - - [11/Feb/2021 19:10:13] "[35m[1mPOST /uploader HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [11/Feb/2021 19:18:35] "[37mGET / HTTP/1.1[0m" 200 -
ERROR:__main__:Exception on /uploader [POST]
Traceback (most recent call last):
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<ipython-input-4-a0bb1ff2dd6b>", line 42, in upload
    return process(f.filename)
  File "<ipython-input-4-a0bb1ff2dd6b>", line 47, in process
    listFinal = gd.startFetchingDetails(filename)
NameError: name 'gd' is not defined
INFO:werkzeug:127.0.0.1 - - [11/Feb/2021 19:18:42] "[35m[1mPOST /uploader HTTP/1.1[0m" 500 -
ERROR:__main__:Exception on /uploader [POST]
Traceback (most recent call last):
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<ipython-input-4-a0bb1ff2dd6b>", line 42, in upload
    return process(f.filename)
  File "<ipython-input-4-a0bb1ff2dd6b>", line 47, in process
    listFinal = gd.startFetchingDetails(filename)
NameError: name 'gd' is not defined
INFO:werkzeug:127.0.0.1 - - [11/Feb/2021 19:18:52] "[35m[1mPOST /uploader HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [11/Feb/2021 19:21:09] "[37mGET / HTTP/1.1[0m" 200 -
ERROR:__main__:Exception on /uploader [POST]
Traceback (most recent call last):
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/arslanzafar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<ipython-input-4-a0bb1ff2dd6b>", line 42, in upload
    return process(f.filename)
  File "<ipython-input-4-a0bb1ff2dd6b>", line 47, in process
    listFinal = gd.startFetchingDetails(filename)
NameError: name 'gd' is not defined
INFO:werkzeug:127.0.0.1 - - [11/Feb/2021 19:21:14] "[35m[1mPOST /uploader HTTP/1.1[0m" 500 -
ERROR:root:Error occured in function fetchCompaniesFromExcelInvalid file path or buffer object type: <class 'pandas.core.frame.DataFrame'>
ERROR:root:Error occured in function fetchDetails'NoneType' object is not iterable
ERROR:root:Error occured in function fetchCompaniesFromExcelInvalid file path or buffer object type: <class 'pandas.core.frame.DataFrame'>
ERROR:root:Error occured in function fetchDetails'NoneType' object is not iterable
ERROR:root:Error occured in function fetchCompaniesFromExcel'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
ERROR:root:Error occured in function fetchDetails'NoneType' object is not iterable
ERROR:root:Error occured in function fetchCompaniesFromExcel'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
ERROR:root:Error occured in function fetchDetails'NoneType' object is not iterable
ERROR:root:Error occured in function fetchCompaniesFromExcel'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
ERROR:root:Error occured in function fetchDetails'NoneType' object is not iterable
ERROR:root:Error occured in function fetchCompaniesFromExcel'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
ERROR:root:Error occured in function fetchDetails'NoneType' object is not iterable
ERROR:root:Error occured in function fetchCompaniesFromExcel'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
ERROR:root:Error occured in function fetchDetails'NoneType' object is not iterable
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
ERROR:root:Error occured in function SearchCompanyMessage: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="MainCol"]/div[1]/div[2]/div[1]/div[2]/div[1]/a"}
  (Session info: chrome=88.0.4324.150)

INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
ERROR:root:Error occured in function SearchCompanyMessage: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="MainCol"]/div[1]/div[2]/div[1]/div[2]/div[1]/a"}
  (Session info: chrome=88.0.4324.150)

INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
ERROR:root:Error occured in function SearchCompanyMessage: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="MainCol"]/div[1]/div[2]/div[1]/div[2]/div[1]/a"}
  (Session info: chrome=88.0.4324.150)

INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
ERROR:root:Error occured in function SearchCompanyMessage: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="MainCol"]/div/div[1]/div/div[1]/div/div[2]/h2/a/font/font"}
  (Session info: chrome=88.0.4324.150)

INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Trying to download new driver from http://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_mac64.zip
INFO:WDM:Driver has been saved in cache [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96]
INFO:WDM:Current google-chrome version is 88.0.4324
INFO:WDM:Get LATEST driver version for 88.0.4324
INFO:WDM:Driver [/Users/arslanzafar/.wdm/drivers/chromedriver/mac64/88.0.4324.96/chromedriver] found in cache
